<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run()
    {
        $cities = [
            "Sabang",
            "Banda Aceh",
            "Lhokseumawe",
            "Langsa",
            "Subulussalam",
            "Medan",
            "Pematangsiantar",
            "Sibolga",
            "Tanjungbalai",
            "Binjai",
            "Tebing Tinggi",
            "Padangsidempuan",
            "Gunungsitoli",
            "Padang",
            "Solok",
            "Sawahlunto",
            "Padang Panjang",
            "Bukittinggi",
            "Payakumbuh",
            "Pariaman",
            "Pekanbaru",
            "Dumai",
            "Batam",
            "Tanjungpinang",
            "Jambi",
            "Sungai Penuh",
            "Palembang",
            "Pagar Alam",
            "Lubuklinggau",
            "Prabumulih",
            "Bengkulu",
            "Bandar Lampung",
            "Metro",
            "Pangkalpinang",
            "Tanjung Pandan",
            "Serang",
            "Cilegon",
            "Tangerang",
            "Tangerang Selatan",
            "Jakarta (Jakarta Pusat, Jakarta Utara, Jakarta Barat, Jakarta Selatan, Jakarta Timur)",
            "Bogor",
            "Sukabumi",
            "Bandung",
            "Cirebon",
            "Bekasi",
            "Depok",
            "Tasikmalaya",
            "Banjar",
            "Semarang",
            "Salatiga",
            "Magelang",
            "Surakarta",
            "Pekalongan",
            "Tegal",
            "Cilacap",
            "Purwokerto",
            "Yogyakarta",
            "Surabaya",
            "Malang",
            "Kediri",
            "Blitar",
            "Madiun",
            "Mojokerto",
            "Pasuruan",
            "Probolinggo",
            "Batu",
            "Denpasar",
            "Mataram",
            "Bima",
            "Kupang",
            "Pontianak",
            "Singkawang",
            "Palangka Raya",
            "Banjarmasin",
            "Banjarbaru",
            "Samarinda",
            "Balikpapan",
            "Bontang",
            "Tarakan",
            "Nusantara (IKN)",
            "Manado",
            "Bitung",
            "Tomohon",
            "Kotamobagu",
            "Palu",
            "Kendari",
            "Baubau",
            "Makassar",
            "Parepare",
            "Palopo",
            "Gorontalo",
            "Palu",
            "Mamuju",
            "Ambon",
            "Tual",
            "Ternate",
            "Tidore Kepulauan",
            "Jayapura",
            "Sorong",
            "Merauke",
            "Timika"
        ];

        foreach ($cities as $city) {
            $this->db->table('cities')->insert(['name' => $city]);
        }
    }
}
